mods:
  - screepsmod-auth
  - /mods/screepsmod-admin-utils
  # - tiennou/screepsmod-admin-utils#fix/log-config
  - /mods/screepsmod-mongo
  - /mods/screepsmod-dynamicmarket
  - /mods/screepsmod-history
  - /mods/screepsmod-map-tool
  # - /mods/screepsmod-portals
  - /mods/screepsmod-punxsutawney
  # - glitchassassin/screepsmod-konami#patch-1
bots:
  # simplebot: screepsbot-zeswarm
  # overmind: screeps-bot-overmind
  # tooangel: git+https://github.com/TooAngel/screeps
  # commiebot: 'the-international-screeps-bot'

launcherOptions:
  # If set, automatically ensures all mods are updated
  autoUpdate: false
  # If set, forward console messages to terminal
  logConsole: true
  # The number of parallel runner threads in which player scripts are executed.
  # Don't set this option greater than the number of your physical CPU cores.
  runnerThreads: 1
  # The number of room processor worker processes to launch.
  # Don't set this option greater than the number of your physical CPU cores.
  processorCount: 1

serverConfig:
  map: random_1x1 # utils.importMap will be called automatically with this value, see utils.importMap above
  tickRate: 1000
  socketUpdateRate: 1000
  whitelist: # Does not restrict login, only restricts spawning
    - traxus
    - zeswarm
    - commiebot
    - jackbot
    - nolanbot
    - hunterbot

  shardName: traxusworld
  # constants:
    # UPGRADE_POWER: 10
    # POWER_CREEP_SPAWN_COOLDOWN: 3600000 # 1 Hour
    # POWER_CREEP_DELETE_COOLDOWN: 3600000
  welcomeText: |
    <h1>Welcome</h1>
    <div>Powered by screepsmod-admin-utils</div>
  # statsToken: ...splusToken... # This enables submitting stats to S+ Grafana. Note: shardName MUST be set
  # gclToCPU: true
  # maxCPU: 100
  # baseCPU: 20
  # stepCPU: 10

  portals:
    maxPairs: 5
    distance: [10, 15]
    chance:

  punxsutawney:
    loopDuration: 30
