mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
bots:
  simplebot: screepsbot-zeswarm

launcherOptions:
  # If set, automatically ensures all mods are updated
  autoUpdate: false
  # If set, forward console messages to terminal
  logConsole: false
  custom:
    engine: https://github.com/tiennou/engine#fix/streamline-isActive
    driver: https://github.com/tiennou/driver#fix/getUsed-torn-read
