# Thunderdrone 2
services:
  screeps:
    image: ghcr.io/jomik/screeps-server:edge
    depends_on:
      - mongo
      - redis
    ports:
      - 22025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-user:/home/node
      - screeps-data:/data
      - screeps-mods:/screeps/mods
      - ./dynamicMarketConfig.js:/screeps/dynamicMarketConfig.js
    environment:
      NODE_OPTIONS: --max-old-space-size=4096 --trace-warnings
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
      HISTORY_PATH: /data/history
      HISTORY_KEEP_TICKS: 4000000
      MAPTOOL_USER: ${MAPTOOL_USER}
      MAPTOOL_PASS: ${MAPTOOL_PASS}
    restart: unless-stopped
    build: server
    networks:
      - traefik-net
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.screepsThunderdrone.rule=Host(`td2.pandascreeps.com`)"
      - "traefik.http.routers.screepsThunderdrone.entrypoints=websecure"
      - "traefik.http.routers.screepsThunderdrone.tls.certresolver=letsencrypt"
      - "traefik.http.services.screepsThunderdrone.loadbalancer.server.port=21025"

  mongo:
    image: mongo:4.4.30
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    command: --appendonly yes --save ''
    restart: unless-stopped

volumes:
  screeps-data:
  screeps-mods:
  screeps-user:
  redis-data:
  mongo-data:

networks:
  traefik-net:
    external: true
